<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Kegiatan;

class JadwalPertandinganSeeder extends Seeder
{
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('jadwal_pertandingans')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
        
        $kegiatan = Kegiatan::where('nama_kegiatan', 'PORPROV Banten Ke-VII')->first();
        $kegiatan_id = $kegiatan ? $kegiatan->id : 2; // Fallback to 2

        $jadwals = [
            ['tanggal' => '2026-11-13', 'cabor' => 'Cricket', 'venue' => 'Lap. Rempas', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-13', 'cabor' => 'Hoki', 'venue' => 'Dewantara Sport Center', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-13', 'cabor' => 'Menembak', 'venue' => 'WTC MALL ARHANUD', 'nakes' => ''],
            ['tanggal' => '2026-11-13', 'cabor' => 'Sepak Bola', 'venue' => 'LAP bola KERA SAKTI', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-13', 'cabor' => 'Sepak Bola', 'venue' => 'KODIKLAT TNI', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-13', 'cabor' => 'Pentathlon', 'venue' => 'DAMAI INDAH GOLF BSD', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-14', 'cabor' => 'Balap Motor', 'venue' => 'DIRLANTAS', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-14', 'cabor' => 'Balap Motor', 'venue' => 'SERPONG PARADISE', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-14', 'cabor' => 'Balap Motor', 'venue' => 'TERAS KOTA', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-14', 'cabor' => 'Cricket', 'venue' => 'Lap. Rempas', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-14', 'cabor' => 'Hoki', 'venue' => 'Dewantara Sport Center', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-14', 'cabor' => 'Menembak', 'venue' => 'WTC MALL ARHANUD', 'nakes' => ''],
            ['tanggal' => '2026-11-14', 'cabor' => 'Panahan', 'venue' => 'ISCI International Sports Club of Indonesia', 'nakes' => ''],
            ['tanggal' => '2026-11-14', 'cabor' => 'Pentathlon', 'venue' => 'DAMAI INDAH GOLF BSD', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-14', 'cabor' => 'Sepak Bola', 'venue' => 'LAP bola KERA SAKTI', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-14', 'cabor' => 'Sepak Bola', 'venue' => 'KODIKLAT TNI', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-14', 'cabor' => 'Softball', 'venue' => 'Griya Hijau Alam Sutera', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-16', 'cabor' => 'Catur', 'venue' => 'BLANDONGAN', 'nakes' => ''],
            ['tanggal' => '2026-11-16', 'cabor' => 'Cricket', 'venue' => 'Lap. Rempas', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-16', 'cabor' => 'Hoki', 'venue' => 'Dewantara Sport Center', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-16', 'cabor' => 'Menembak', 'venue' => 'WTC MALL ARHANUD', 'nakes' => ''],
            ['tanggal' => '2026-11-16', 'cabor' => 'Panahan', 'venue' => 'ISCI International Sports Club of Indonesia', 'nakes' => ''],
            ['tanggal' => '2026-11-16', 'cabor' => 'Squash', 'venue' => 'ISCI International Sports Club of Indonesia', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-16', 'cabor' => 'Panjat Tebing', 'venue' => 'PCC', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-16', 'cabor' => 'Pentathlon', 'venue' => 'DAMAI INDAH GOLF BSD', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-16', 'cabor' => 'Sepak Bola', 'venue' => 'LAP bola KERA SAKTI', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-16', 'cabor' => 'Sepak Bola', 'venue' => 'KODIKLAT TNI', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-16', 'cabor' => 'Softball', 'venue' => 'Griya Hijau Alam Sutera', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-17', 'cabor' => 'Anggar', 'venue' => 'UMJ', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-17', 'cabor' => 'Drumband', 'venue' => 'KODIKLAT TNI', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-17', 'cabor' => 'Atletik', 'venue' => 'KODIKLAT TNI', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-17', 'cabor' => 'Barongsai', 'venue' => 'PLAZA PEMKOT', 'nakes' => ''],
            ['tanggal' => '2026-11-17', 'cabor' => 'Billiard', 'venue' => 'JFlowers Billiard BSD City', 'nakes' => ''],
            ['tanggal' => '2026-11-17', 'cabor' => 'Bola Basket', 'venue' => 'MS Sports Arena', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-17', 'cabor' => 'Bola Tangan', 'venue' => 'GIS', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-17', 'cabor' => 'Bola Voli', 'venue' => 'UIN', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-17', 'cabor' => 'Bowling', 'venue' => 'WTC', 'nakes' => ''],
            ['tanggal' => '2026-11-17', 'cabor' => 'Catur', 'venue' => 'BLANDONGAN', 'nakes' => ''],
            ['tanggal' => '2026-11-17', 'cabor' => 'Bridge', 'venue' => 'BLANDONGAN', 'nakes' => ''],
            ['tanggal' => '2026-11-17', 'cabor' => 'Bulu Tangkis', 'venue' => 'CANDRA WIJAYA badminton center', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-17', 'cabor' => 'Cricket', 'venue' => 'Lap. Rempas', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-17', 'cabor' => 'Dance Sport', 'venue' => 'BEXCANGE MALL', 'nakes' => ''],
            ['tanggal' => '2026-11-17', 'cabor' => 'Dayung', 'venue' => 'SITU PONDOK JAGUNG', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-17', 'cabor' => 'Esport', 'venue' => 'GEDUNG UMKM', 'nakes' => ''],
            ['tanggal' => '2026-11-17', 'cabor' => 'Futsal', 'venue' => 'PCC', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-17', 'cabor' => 'Golf', 'venue' => 'PONDOK CABE GOLF', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-17', 'cabor' => 'Senam', 'venue' => 'BRITISH SCHOOL', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-17', 'cabor' => 'Hoki', 'venue' => 'Dewantara Sport Center', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-17', 'cabor' => 'Judo', 'venue' => 'TERAS KOTA', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-17', 'cabor' => 'Karate', 'venue' => 'TERAS KOTA', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-17', 'cabor' => 'Tinju', 'venue' => 'TERAS KOTA', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-17', 'cabor' => 'Kempo', 'venue' => 'KODIKLAT TNI', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-17', 'cabor' => 'Sepak Bola', 'venue' => 'KODIKLAT TNI', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-17', 'cabor' => 'Kurash', 'venue' => 'GOR BRIN', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-17', 'cabor' => 'Menembak', 'venue' => 'WTC MALL ARHANUD', 'nakes' => ''],
            ['tanggal' => '2026-11-17', 'cabor' => 'Muaythai', 'venue' => 'WTC', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-17', 'cabor' => 'Panahan', 'venue' => 'ISCI International Sports Club of Indonesia', 'nakes' => ''],
            ['tanggal' => '2026-11-17', 'cabor' => 'Panjat Tebing', 'venue' => 'PCC', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-17', 'cabor' => 'Pencak Silat', 'venue' => 'GOR BRIN', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-17', 'cabor' => 'Petanque', 'venue' => 'KEC PONDOK AREN', 'nakes' => ''],
            ['tanggal' => '2026-11-17', 'cabor' => 'Pickleball', 'venue' => 'RDM', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-17', 'cabor' => 'Sambo', 'venue' => 'MD SPORT BULUTANGKIS DAN FUTSAL', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-17', 'cabor' => 'Selam', 'venue' => 'DAMAI INDAH GOLF BSD', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-17', 'cabor' => 'Selancar', 'venue' => 'SAWARNA', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-17', 'cabor' => 'Sepak Bola', 'venue' => 'LAP bola KERA SAKTI', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-17', 'cabor' => 'Tenis Meja', 'venue' => 'LOKAL PADEL', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-17', 'cabor' => 'Sepak Takraw', 'venue' => 'LOKAL PADEL', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-17', 'cabor' => 'Sepatu Roda', 'venue' => 'CIATER PERMAI', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-17', 'cabor' => 'Softball', 'venue' => 'Griya Hijau Alam Sutera', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-17', 'cabor' => 'Squash', 'venue' => 'ISCI International Sports Club of Indonesia', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-17', 'cabor' => 'Tenis Lapangan', 'venue' => 'LAP KONI', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-17', 'cabor' => 'Woodball', 'venue' => 'GOR BRIN', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-17', 'cabor' => 'Wushu', 'venue' => 'PLAZA PEMKOT', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-18', 'cabor' => 'Anggar', 'venue' => 'UMJ', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Atletik', 'venue' => 'KODIKLAT TNI', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Kempo', 'venue' => 'KODIKLAT TNI', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Drumband', 'venue' => 'KODIKLAT TNI', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Barongsai', 'venue' => 'PLAZA PEMKOT', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Billiard', 'venue' => 'JFlowers Billiard BSD City', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Bola Basket', 'venue' => 'MS Sports Arena', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Bola Tangan', 'venue' => 'GIS', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Bola Voli', 'venue' => 'UIN', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Bowling', 'venue' => 'WTC', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Muaythai', 'venue' => 'WTC', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Menembak', 'venue' => 'WTC MALL ARHANUD', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Bridge', 'venue' => 'BLANDONGAN', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Catur', 'venue' => 'BLANDONGAN', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Bulu Tangkis', 'venue' => 'CANDRA WIJAYA badminton center', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Cricket', 'venue' => 'Lap. Rempas', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Dance Sport', 'venue' => 'BEXCANGE MALL', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Dayung', 'venue' => 'SITU PONDOK JAGUNG', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Esport', 'venue' => 'GEDUNG UMKM', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Futsal', 'venue' => 'PCC', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Panjat Tebing', 'venue' => 'PCC', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Golf', 'venue' => 'PONDOK CABE GOLF', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Senam', 'venue' => 'BRITISH SCHOOL', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Hoki', 'venue' => 'Dewantara Sport Center', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Judo', 'venue' => 'TERAS KOTA', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Karate', 'venue' => 'TERAS KOTA', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Tinju', 'venue' => 'TERAS KOTA', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Kurash', 'venue' => 'GOR BRIN', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Woodball', 'venue' => 'GOR BRIN', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Pencak Silat', 'venue' => 'GOR BRIN', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Panahan', 'venue' => 'ISCI International Sports Club of Indonesia', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Squash', 'venue' => 'ISCI International Sports Club of Indonesia', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Petanque', 'venue' => 'KEC PONDOK AREN', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Pickleball', 'venue' => 'RDM', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Sambo', 'venue' => 'MD SPORT BULUTANGKIS DAN FUTSAL', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Selam', 'venue' => 'DAMAI INDAH GOLF BSD', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Selancar', 'venue' => 'SAWARNA', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Sepak Bola', 'venue' => 'LAP bola KERA SAKTI', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Sepak Takraw', 'venue' => 'LOKAL PADEL', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Tenis Meja', 'venue' => 'LOKAL PADEL', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Sepatu Roda', 'venue' => 'CIATER PERMAI', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Softball', 'venue' => 'Griya Hijau Alam Sutera', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Tenis Lapangan', 'venue' => 'LAP KONI', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Wushu', 'venue' => 'PLAZA PEMKOT', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Anggar', 'venue' => 'UMJ', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Angkat Berat', 'venue' => 'AULA KEC PONDOK AREN', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Angkat Besi', 'venue' => 'ITC BSD', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Arung Jeram', 'venue' => 'Ekowisata Kranggan', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Atletik', 'venue' => 'KODIKLAT TNI', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Drumband', 'venue' => 'KODIKLAT TNI', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Kempo', 'venue' => 'KODIKLAT TNI', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Sepak Bola', 'venue' => 'KODIKLAT TNI', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Barongsai', 'venue' => 'PLAZA PEMKOT', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Billiard', 'venue' => 'JFlowers Billiard BSD City', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Bola Basket', 'venue' => 'MS Sports Arena', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Bola Tangan', 'venue' => 'GIS', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Bola Voli', 'venue' => 'UIN', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Bowling', 'venue' => 'WTC', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Bridge', 'venue' => 'BLANDONGAN', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Catur', 'venue' => 'BLANDONGAN', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Bulu Tangkis', 'venue' => 'CANDRA WIJAYA badminton center', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Cricket', 'venue' => 'Lap. Rempas', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Dayung', 'venue' => 'SITU PONDOK JAGUNG', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Esport', 'venue' => 'GEDUNG UMKM', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Futsal', 'venue' => 'PCC', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Rugby', 'venue' => 'PCC', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Panjat Tebing', 'venue' => 'PCC', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Golf', 'venue' => 'PONDOK CABE GOLF', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Senam', 'venue' => 'BRITISH SCHOOL', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Hoki', 'venue' => 'Dewantara Sport Center', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Karate', 'venue' => 'TERAS KOTA', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Tinju', 'venue' => 'TERAS KOTA', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Muaythai', 'venue' => 'WTC', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Panahan', 'venue' => 'ISCI International Sports Club of Indonesia', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Pencak Silat', 'venue' => 'GOR BRIN', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Petanque', 'venue' => 'KEC PONDOK AREN', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Pickleball', 'venue' => 'RDM', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Selancar', 'venue' => 'SAWARNA', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Sepak Bola', 'venue' => 'LAP bola KERA SAKTI', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Tenis Meja', 'venue' => 'LOKAL PADEL', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Sepak Takraw', 'venue' => 'LOKAL PADEL', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Sepatu Roda', 'venue' => 'CIATER PERMAI', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Softball', 'venue' => 'Griya Hijau Alam Sutera', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Squash', 'venue' => 'ISCI International Sports Club of Indonesia', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Tenis Lapangan', 'venue' => 'LAP KONI', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Woodball', 'venue' => 'GOR BRIN', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Wushu', 'venue' => 'PLAZA PEMKOT', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Anggar', 'venue' => 'UMJ', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Angkat Berat', 'venue' => 'AULA KEC PONDOK AREN', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Angkat Besi', 'venue' => 'ITC BSD', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Renang', 'venue' => 'DAMAI INDAH GOLF BSD', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Arung Jeram', 'venue' => 'Ekowisata Kranggan', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Barongsai', 'venue' => 'PLAZA PEMKOT', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Wushu', 'venue' => 'PLAZA PEMKOT', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Billiard', 'venue' => 'JFlowers Billiard BSD City', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Bola Basket', 'venue' => 'MS Sports Arena', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Bola Tangan', 'venue' => 'GIS', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Bola Voli', 'venue' => 'UIN', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Bowling', 'venue' => 'WTC', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Bridge', 'venue' => 'BLANDONGAN', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Catur', 'venue' => 'BLANDONGAN', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Bulu Tangkis', 'venue' => 'CANDRA WIJAYA badminton center', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Cricket', 'venue' => 'Lap. Rempas', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Dayung', 'venue' => 'SITU PONDOK JAGUNG', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Sepak Bola', 'venue' => 'KODIKLAT TNI', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Drumband', 'venue' => 'KODIKLAT TNI', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Esport', 'venue' => 'GEDUNG UMKM', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Floorball', 'venue' => 'GIS', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Futsal', 'venue' => 'PCC', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Rugby', 'venue' => 'PCC', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Golf', 'venue' => 'PONDOK CABE GOLF', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Gulat', 'venue' => 'MD SPORT BULUTANGKIS DAN FUTSAL', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Senam', 'venue' => 'BRITISH SCHOOL', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Hoki', 'venue' => 'Dewantara Sport Center', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'MMA', 'venue' => 'GOR CIPUTAT', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Panahan', 'venue' => 'ISCI International Sports Club of Indonesia', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Squash', 'venue' => 'ISCI International Sports Club of Indonesia', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Panjat Tebing', 'venue' => 'PCC', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Pencak Silat', 'venue' => 'GOR BRIN', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Tarung Derajat', 'venue' => 'GOR BRIN', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Woodball', 'venue' => 'GOR BRIN', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Petanque', 'venue' => 'KEC PONDOK AREN', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Selancar', 'venue' => 'SAWARNA', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Sepak Bola', 'venue' => 'LAP bola KERA SAKTI', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Tenis Meja', 'venue' => 'LOKAL PADEL', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Sepak Takraw', 'venue' => 'LOKAL PADEL', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Sepatu Roda', 'venue' => 'CIATER PERMAI', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Softball', 'venue' => 'Griya Hijau Alam Sutera', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Taekwondo', 'venue' => '-', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Tenis Lapangan', 'venue' => 'LAP KONI', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Angkat Besi', 'venue' => 'ITC BSD', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Renang', 'venue' => 'DAMAI INDAH GOLF BSD', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Arung Jeram', 'venue' => 'Ekowisata Kranggan', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Barongsai', 'venue' => 'PLAZA PEMKOT', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Balap Motor', 'venue' => 'DIRLANTAS', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Balap Motor', 'venue' => 'SERPONG PARADISE', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Balap Motor', 'venue' => 'TERAS KOTA', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Billiard', 'venue' => 'JFlowers Billiard BSD City', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Bola Basket', 'venue' => 'MS Sports Arena', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Bola Tangan', 'venue' => 'GIS', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Floorball', 'venue' => 'GIS', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Bridge', 'venue' => 'BLANDONGAN', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Catur', 'venue' => 'BLANDONGAN', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Bulu Tangkis', 'venue' => 'CANDRA WIJAYA badminton center', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Cricket', 'venue' => 'Lap. Rempas', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Dayung', 'venue' => 'SITU PONDOK JAGUNG', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Drumband', 'venue' => 'KODIKLAT TNI', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Sepak Bola', 'venue' => 'KODIKLAT TNI', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Gateball', 'venue' => 'KAMPUS KADEMANGAN', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Golf', 'venue' => 'PONDOK CABE GOLF', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Gulat', 'venue' => 'MD SPORT BULUTANGKIS DAN FUTSAL', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Senam', 'venue' => 'BRITISH SCHOOL', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Hoki', 'venue' => 'Dewantara Sport Center', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'MMA', 'venue' => 'GOR CIPUTAT', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Jujitsu', 'venue' => 'GOR CIPUTAT', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Panahan', 'venue' => 'ISCI International Sports Club of Indonesia', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Squash', 'venue' => 'ISCI International Sports Club of Indonesia', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Rugby', 'venue' => 'PCC', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Panjat Tebing', 'venue' => 'PCC', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Futsal', 'venue' => 'PCC', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Petanque', 'venue' => 'KEC PONDOK AREN', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Sepak Bola', 'venue' => 'LAP bola KERA SAKTI', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Sepatu Roda', 'venue' => 'CIATER PERMAI', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Softball', 'venue' => 'Griya Hijau Alam Sutera', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Taekwondo', 'venue' => '-', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Tarung Derajat', 'venue' => 'GOR BRIN', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Woodball', 'venue' => 'GOR BRIN', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Pencak Silat', 'venue' => 'GOR BRIN', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Tenis Lapangan', 'venue' => 'LAP KONI', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Tenis Meja', 'venue' => 'LOKAL PADEL', 'nakes' => ''],
            ['tanggal' => '2026-11-22', 'cabor' => 'Renang', 'venue' => 'DAMAI INDAH GOLF BSD', 'nakes' => ''],
            ['tanggal' => '2026-11-22', 'cabor' => 'Arung Jeram', 'venue' => 'Ekowisata Kranggan', 'nakes' => ''],
            ['tanggal' => '2026-11-22', 'cabor' => 'Balap Motor', 'venue' => 'DIRLANTAS', 'nakes' => ''],
            ['tanggal' => '2026-11-22', 'cabor' => 'Balap Motor', 'venue' => 'SERPONG PARADISE', 'nakes' => ''],
            ['tanggal' => '2026-11-22', 'cabor' => 'Balap Motor', 'venue' => 'TERAS KOTA', 'nakes' => ''],
            ['tanggal' => '2026-11-22', 'cabor' => 'Bina Raga', 'venue' => 'TERAS KOTA', 'nakes' => ''],
            ['tanggal' => '2026-11-22', 'cabor' => 'Bola Tangan', 'venue' => 'GIS', 'nakes' => ''],
            ['tanggal' => '2026-11-22', 'cabor' => 'Bridge', 'venue' => 'BLANDONGAN', 'nakes' => ''],
            ['tanggal' => '2026-11-22', 'cabor' => 'Catur', 'venue' => 'BLANDONGAN', 'nakes' => ''],
            ['tanggal' => '2026-11-22', 'cabor' => 'Bulu Tangkis', 'venue' => 'CANDRA WIJAYA badminton center', 'nakes' => ''],
            ['tanggal' => '2026-11-22', 'cabor' => 'Cricket', 'venue' => 'Lap. Rempas', 'nakes' => ''],
            ['tanggal' => '2026-11-22', 'cabor' => 'Dayung', 'venue' => 'SITU PONDOK JAGUNG', 'nakes' => ''],
            ['tanggal' => '2026-11-22', 'cabor' => 'Drumband', 'venue' => 'KODIKLAT TNI', 'nakes' => ''],
            ['tanggal' => '2026-11-22', 'cabor' => 'Floorball', 'venue' => 'GIS', 'nakes' => ''],
            ['tanggal' => '2026-11-22', 'cabor' => 'Gateball', 'venue' => 'KAMPUS KADEMANGAN', 'nakes' => ''],
            ['tanggal' => '2026-11-22', 'cabor' => 'Gulat', 'venue' => 'MD SPORT BULUTANGKIS DAN FUTSAL', 'nakes' => ''],
            ['tanggal' => '2026-11-22', 'cabor' => 'Hoki', 'venue' => 'Dewantara Sport Center', 'nakes' => ''],
            ['tanggal' => '2026-11-22', 'cabor' => 'MMA', 'venue' => 'GOR CIPUTAT', 'nakes' => ''],
            ['tanggal' => '2026-11-22', 'cabor' => 'Panahan', 'venue' => 'ISCI International Sports Club of Indonesia', 'nakes' => ''],
            ['tanggal' => '2026-11-22', 'cabor' => 'Squash', 'venue' => 'ISCI International Sports Club of Indonesia', 'nakes' => ''],
            ['tanggal' => '2026-11-22', 'cabor' => 'Panjat Tebing', 'venue' => 'PCC', 'nakes' => ''],
            ['tanggal' => '2026-11-22', 'cabor' => 'Rugby', 'venue' => 'PCC', 'nakes' => ''],
            ['tanggal' => '2026-11-22', 'cabor' => 'Futsal', 'venue' => 'PCC', 'nakes' => ''],
            ['tanggal' => '2026-11-22', 'cabor' => 'Sepak Bola', 'venue' => 'LAP bola KERA SAKTI', 'nakes' => ''],
            ['tanggal' => '2026-11-22', 'cabor' => 'Sepatu Roda', 'venue' => 'CIATER PERMAI', 'nakes' => ''],
            ['tanggal' => '2026-11-22', 'cabor' => 'Softball', 'venue' => 'Griya Hijau Alam Sutera', 'nakes' => ''],
            ['tanggal' => '2026-11-22', 'cabor' => 'Tarung Derajat', 'venue' => 'GOR BRIN', 'nakes' => ''],
            ['tanggal' => '2026-11-22', 'cabor' => 'Woodball', 'venue' => 'GOR BRIN', 'nakes' => ''],
        ];

        $venue_mapping = [
            'PCC' => ['alamat' => 'Surya Kencana, Pamulang Barat, Kecamatan Pamulang, Kota Tangerang Selatan, Banten', 'gmap' => 'https://maps.app.goo.gl/qpTZZrchfQhA8wPA'],
            'PONDOK CABE GOLF' => ['alamat' => 'Jalan Pondok Cabe Golf (atau Jalan Cabe Raya), Pondok Cabe Udik/Ilir, Kecamatan Pamulang, Kota Tangerang Selatan, Banten', 'gmap' => 'https://maps.app.goo.gl/pUKkicTbW1dpg2A9R8'],
            'Griya Hijau Alam Sutera' => ['alamat' => 'Jl. Griya Hijau Raya, Pakualam, Kec. Serpong Utara, Kota Tangerang Selatan, Banten 15320', 'gmap' => 'https://maps.app.goo.gl/7SxXxTRKqX1i19DT8'],
            'KAMPUS KADEMANGAN' => ['alamat' => '', 'gmap' => ''],
            'Ekowisata Kranggan' => ['alamat' => 'Jl. Lkr. Selatan, Kranggan, Kec. Setu, Kota Tangerang Selatan, Banten 15312', 'gmap' => 'https://maps.app.goo.gl/uiE8ZVqs1HdfqgGx79'],
            'ISCI International Sports Club of Indonesia' => ['alamat' => 'MQR5+7QV, Jl. Ciputat Raya No.2, Cireundeu, Kec. Ciputat Tim., Kota Tangerang Selatan, Banten 15419', 'gmap' => 'https://maps.app.goo.gl/qQ3EMptE2tKRrHTLA'],
            'LAP bola KERA SAKTI' => ['alamat' => 'JMVH+X5X, Setu, Kec. Setu, Kota Tangerang Selatan, Banten 15314', 'gmap' => 'https://maps.app.goo.gl/p7nrscJXdThXzkKJCJ6'],
            'Dewantara Sport Center' => ['alamat' => 'Victor, Jl. Buaran raya No.62, RT.02/RW.01, Buaran, Kec. Serpong, Kota Tangerang Selatan, Banten 15310', 'gmap' => 'https://maps.app.goo.gl/RErVTQTrN1e8Ndj97'],
            'KEC PONDOK AREN' => ['alamat' => 'Jl. Graha Raya Bintaro No.1, Parigi Baru, Tangerang, Kota Tangerang Selatan, Banten 15228', 'gmap' => 'https://maps.app.goo.gl/xAtFfqcbW3L85YbB6'],
            'CANDRA WIJAYA badminton center' => ['alamat' => 'Jl. Jelupang Raya No.15, Jelupang, Kec. Serpong Utara, Kota Tangerang Selatan, Banten 15323', 'gmap' => 'https://maps.app.goo.gl/pM2LEMEGYdJohFw9'],
            'LAP KONI' => ['alamat' => 'Jl. Bintaro Utama Sektor 3A, Pd. Karya, Kec. Pd. Aren, Kota Tangerang Selatan, Banten 15225', 'gmap' => 'https://maps.app.goo.gl/cniL29LoeK3Euxs8'],
            'JFlowers Billiard BSD City' => ['alamat' => 'Lengkong Wetan, Kec. Serpong, Kota Tangerang Selatan, Banten 15310', 'gmap' => 'https://maps.app.goo.gl/BcsuE3UU3Jwd2ig7'],
            'SAWARNA' => ['alamat' => '', 'gmap' => ''],
            'DIRLANTAS' => ['alamat' => '', 'gmap' => ''],
            'SERPONG PARADISE' => ['alamat' => '', 'gmap' => ''],
            'RDM' => ['alamat' => 'Perumahan Serua Makmur Blok 28 No. 7, Serua, Ciputat, Tangerang Selatan, Banten', 'gmap' => ''],
            'Lap. Rempas' => ['alamat' => 'Jl. Kp. No.25, Babakan, Kec. Setu, Kota Tangerang Selatan, Banten 15315', 'gmap' => 'https://maps.app.goo.gl/qkbandAMq8RzGgHw5'],
            'AULA KEC PONDOK AREN' => ['alamat' => '', 'gmap' => ''],
            'SITU PONDOK JAGUNG' => ['alamat' => 'Jl. Rawa Putus, Pd. Jagung Tim., Kec. Serpong Utara, Kota Tangerang Selatan, Banten 15326', 'gmap' => 'https://maps.app.goo.gl/U9cqTNgatvCqrA3'],
            'BEXCANGE MALL' => ['alamat' => 'Bintaro Jaya Sektor 7, Jl. Lkr. Jaya, Pd. Jaya, Kec. Pd. Aren, Kota Tangerang Selatan, Banten 15220', 'gmap' => 'https://maps.app.goo.gl/AGtXccTuxA7xJU6'],
            'UIN' => ['alamat' => '', 'gmap' => ''],
            'UMJ' => ['alamat' => '', 'gmap' => ''],
            'ITC BSD' => ['alamat' => 'Jl. Pahlawan Seribu No.12, Lengkong Wetan, Kec. Serpong, Kota Tangerang Selatan, Banten 15310', 'gmap' => 'https://maps.app.goo.gl/uCNGWU2zeTr5pLuH7'],
            'MS Sports Arena' => ['alamat' => 'Gading Ocean Walk, Jl. Pahlawan Seribu Blok CBD LOT No.VI A, Lengkong Gudang, Kec. Serpong, Kota Tangerang Selatan, Banten 15320', 'gmap' => 'https://maps.app.goo.gl/dbzLPK911n2vGLjC6'],
            'WTC MALL ARHANUD' => ['alamat' => 'Jl. Raya Serpong Kilometer 7, Pd. Jagung, Kec. Serpong Utara, Kota Tangerang Selatan, Banten 15326', 'gmap' => 'https://maps.app.goo.gl/UoTzNeFyY9n1vLnd6'],
            'CIATER PERMAI' => ['alamat' => '', 'gmap' => ''],
            'GEDUNG UMKM' => ['alamat' => 'Jl. Sunburst CBD, Lengkong Gudang, Kec. Serpong, Kota Tangerang Selatan, Banten 15321', 'gmap' => 'https://maps.app.goo.gl/qZQQdRsa2ofAaXk9'],
            'BRITISH SCHOOL' => ['alamat' => 'Jl. Jombang Raya No.9, Pd. Pucung, Kec. Pd. Aren, Kota Tangerang Selatan, Banten 15227', 'gmap' => 'https://maps.app.goo.gl/qZFRtt12o2wkYm1HLA'],
            'MD SPORT BULUTANGKIS DAN FUTSAL' => ['alamat' => 'MP8Q+7MP, Jl. Sinar Pamulang Permai, Pamulang Bar., Kec. Pamulang, Kota Tangerang Selatan, Banten 15417', 'gmap' => 'https://maps.app.goo.gl/rnRbSu1LQB2tmw1R6'],
            'PLAZA PEMKOT' => ['alamat' => 'Jl. Adi Sengkong Blok A No.8, Serua, Kec. Ciputat, Kota Tangerang Selatan, Banten 15414', 'gmap' => 'https://maps.app.goo.gl/uYFGrGaqH6Fhww6'],
            'BLANDONGAN' => ['alamat' => '', 'gmap' => ''],
            'WTC' => ['alamat' => '', 'gmap' => ''],
            'LOKAL PADEL' => ['alamat' => 'Loka Padel, Jl. Tandon Ciater, Ciater, Serpong Sub-District, South Tangerang City, Banten 15310', 'gmap' => 'https://maps.app.goo.gl/Jq1VzTDVDg84N87'],
            'GOR CIPUTAT' => ['alamat' => 'Jl. Pemuda No.2, Ciputat, Kec. Ciputat, Kota Tangerang Selatan, Banten 15411', 'gmap' => 'https://maps.app.goo.gl/hPbtkk8YU5EXZrX8'],
            'GIS' => ['alamat' => 'Jl. Raya Puspitek No.10, Buaran, Kec. Serpong, Kota Tangerang Selatan, Banten 15310', 'gmap' => 'https://maps.app.goo.gl/teJ7T8BGETdz3Rq8'],
            'DAMAI INDAH GOLF BSD' => ['alamat' => 'Jl. Bukit Golf I BSD Sektor VI, Lengkong Karya, Kec. Serpong Utara, Kota Tangerang Selatan, Banten 15310', 'gmap' => 'https://maps.app.goo.gl/eHfVp2hDcV5Puzh45'],
            'KODIKLAT TNI' => ['alamat' => 'Jl. Kediklat Tni Ampera, Buaran, Kec. Serpong, Kota Tangerang Selatan, Banten 15310', 'gmap' => 'https://maps.app.goo.gl/umnxVKqTDKaHKYSA'],
            'GOR BRIN' => ['alamat' => 'Blok M 15314, Jl. Garuda 4 Blok A-5 No.10, Bakti Jaya, Setu, South Tangerang City, Banten 15315', 'gmap' => 'https://maps.app.goo.gl/qdajTiZuMTAGBFqp8'],
            'TERAS KOTA' => ['alamat' => 'CBD Lot JI. Pahlawan Seribu No.VII B, Lengkong Gudang, Kec. Serpong, Kota Tangerang Selatan, Banten 15310', 'gmap' => 'https://maps.app.goo.gl/yQurDtEkwUth729'],
        ];
        
        $data = [];
        foreach ($jadwals as $j) {
            $venueName = $j['venue'];
            $alamat = '';
            $gmap = '';
            if (isset($venue_mapping[$venueName])) {
                $alamat = $venue_mapping[$venueName]['alamat'];
                $gmap = $venue_mapping[$venueName]['gmap'];
            }

            $data[] = [
                'kegiatan_id' => $kegiatan_id,
                'jenis_cabor' => $j['cabor'],
                'kel_cabor' => null,
                'venue' => $j['venue'],
                'alamat' => $alamat,
                'link_google_map' => $gmap,
                'jumlah_lapangan' => null,
                'tanggal' => $j['tanggal'],
                'waktu' => '08:00', // Default time as not provided
                'nakes' => $j['nakes'],
                'created_at' => now(),
                'updated_at' => now(),
            ];
        }

        DB::table('jadwal_pertandingans')->insert($data);
    }
}
