<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class NakesAbsenSeeder extends Seeder
{
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('nakes_absens')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $data = [
            [
                'nakes_jaga_id' => 1,
                'nama' => 'dr. Budi Santoso',
                'instansi' => 'RSUD Kota Tangerang',
                'keterangan' => 'Hadir tepat waktu',
                'bank' => 'BCA',
                'norek' => '8765432190',
                'tanda_tangan' => 'https://upload.wikimedia.org/wikipedia/commons/f/fa/Signature_of_John_Hancock.png',
                'foto' => null,
                'created_at' => Carbon::now()->subDays(2)->setHour(7)->setMinute(15),
            ],
            [
                'nakes_jaga_id' => 2,
                'nama' => 'Siti Aminah, S.Kep',
                'instansi' => 'Puskesmas Pamulang',
                'keterangan' => 'Membawa perlengkapan P3K lengkap',
                'bank' => 'Mandiri',
                'norek' => '1640001234567',
                'tanda_tangan' => 'https://upload.wikimedia.org/wikipedia/commons/a/a4/Signature_of_Barack_Obama.svg',
                'foto' => null,
                'created_at' => Carbon::now()->subDays(2)->setHour(7)->setMinute(30),
            ],
            [
                'nakes_jaga_id' => 3,
                'nama' => 'Ahmad Reza, Amd.Kep',
                'instansi' => 'Klinik Sehat Bersama',
                'keterangan' => 'Hadir',
                'bank' => 'BNI',
                'norek' => '0987654321',
                'tanda_tangan' => 'https://upload.wikimedia.org/wikipedia/commons/e/ec/Signature_of_Donald_Trump.svg',
                'foto' => null,
                'created_at' => Carbon::now()->subDays(2)->setHour(7)->setMinute(45),
            ],
            [
                'nakes_jaga_id' => 4,
                'nama' => 'dr. Nisa Pertiwi',
                'instansi' => 'RS Hermina Ciputat',
                'keterangan' => 'Terlambat 15 menit karena macet',
                'bank' => 'BRI',
                'norek' => '321456789012345',
                'tanda_tangan' => 'https://upload.wikimedia.org/wikipedia/commons/6/6f/Signature_of_Hillary_Clinton.svg',
                'foto' => null,
                'created_at' => Carbon::now()->subDays(1)->setHour(8)->setMinute(15),
            ],
            [
                'nakes_jaga_id' => 5,
                'nama' => 'Rahmat Hidayat, S.Kep',
                'instansi' => 'Dinkes Tangsel',
                'keterangan' => 'Hadir',
                'bank' => 'BCA',
                'norek' => '1234567890',
                'tanda_tangan' => 'https://upload.wikimedia.org/wikipedia/commons/0/07/Signature_of_George_Washington.svg',
                'foto' => null,
                'created_at' => Carbon::now()->subDays(1)->setHour(7)->setMinute(20),
            ],
            [
                'nakes_jaga_id' => 6,
                'nama' => 'Dewi Lestari, Amd.Kep',
                'instansi' => 'RS Sari Asih Ciputat',
                'keterangan' => 'Bertugas di medis center',
                'bank' => 'Mandiri',
                'norek' => '1640009876543',
                'tanda_tangan' => 'https://upload.wikimedia.org/wikipedia/commons/8/87/Signature_of_Abraham_Lincoln.svg',
                'foto' => null,
                'created_at' => Carbon::now()->subDays(1)->setHour(7)->setMinute(50),
            ],
            [
                'nakes_jaga_id' => 7,
                'nama' => 'dr. Andika Pratama',
                'instansi' => 'RS IMC Bintaro',
                'keterangan' => 'Hadir',
                'bank' => 'BJB',
                'norek' => '001122334455',
                'tanda_tangan' => 'https://upload.wikimedia.org/wikipedia/commons/2/23/Signature_of_Thomas_Jefferson.svg',
                'foto' => null,
                'created_at' => Carbon::now()->setHour(7)->setMinute(10),
            ],
            [
                'nakes_jaga_id' => 8,
                'nama' => 'Fitriani, S.Kep',
                'instansi' => 'RS Premier Bintaro',
                'keterangan' => 'Hadir membawa ambulans',
                'bank' => 'BCA',
                'norek' => '5678901234',
                'tanda_tangan' => 'https://upload.wikimedia.org/wikipedia/commons/5/52/Signature_of_John_F._Kennedy.svg',
                'foto' => null,
                'created_at' => Carbon::now()->setHour(7)->setMinute(15),
            ],
            [
                'nakes_jaga_id' => 9,
                'nama' => 'M. Rizky, Amd.Kep',
                'instansi' => 'Puskesmas Ciputat Timur',
                'keterangan' => 'Hadir tepat waktu',
                'bank' => 'BNI',
                'norek' => '0123456789',
                'tanda_tangan' => 'https://upload.wikimedia.org/wikipedia/commons/b/b3/Signature_of_Nelson_Mandela.svg',
                'foto' => null,
                'created_at' => Carbon::now()->setHour(7)->setMinute(25),
            ],
            [
                'nakes_jaga_id' => 10,
                'nama' => 'dr. Ratna Mutiara',
                'instansi' => 'RSUD Tangsel',
                'keterangan' => 'Hadir, bertugas di ring 1',
                'bank' => 'BRI',
                'norek' => '098765432109876',
                'tanda_tangan' => 'https://upload.wikimedia.org/wikipedia/commons/a/ab/Signature_of_Richard_Nixon.svg',
                'foto' => null,
                'created_at' => Carbon::now()->setHour(7)->setMinute(35),
            ],
            [
                'nakes_jaga_id' => 11,
                'nama' => 'Arif Budiman, S.Kep',
                'instansi' => 'Klinik Medika',
                'keterangan' => 'Standby di tepi lapangan',
                'bank' => 'Mandiri',
                'norek' => '1640005555555',
                'tanda_tangan' => 'https://upload.wikimedia.org/wikipedia/commons/2/29/Signature_of_Franklin_D._Roosevelt.svg',
                'foto' => null,
                'created_at' => Carbon::now()->setHour(7)->setMinute(40),
            ],
            [
                'nakes_jaga_id' => 12,
                'nama' => 'Indah Cahyani, Amd.Kep',
                'instansi' => 'Puskesmas Serpong',
                'keterangan' => 'Hadir',
                'bank' => 'BJB',
                'norek' => '009988776655',
                'tanda_tangan' => 'https://upload.wikimedia.org/wikipedia/commons/6/69/Signature_of_Alexander_Hamilton.svg',
                'foto' => null,
                'created_at' => Carbon::now()->setHour(7)->setMinute(55),
            ],
            [
                'nakes_jaga_id' => 13,
                'nama' => 'dr. Hendra Setiawan',
                'instansi' => 'RS Eka Hospital BSD',
                'keterangan' => 'Hadir',
                'bank' => 'BCA',
                'norek' => '1122334455',
                'tanda_tangan' => 'https://upload.wikimedia.org/wikipedia/commons/1/15/Signature_of_Albert_Einstein.svg',
                'foto' => null,
                'created_at' => Carbon::now()->subDays(3)->setHour(8)->setMinute(0),
            ],
            [
                'nakes_jaga_id' => 14,
                'nama' => 'Yulia Putri, S.Kep',
                'instansi' => 'RS Medika BSD',
                'keterangan' => 'Bertugas di Posko Kesehatan',
                'bank' => 'BNI',
                'norek' => '5555444433',
                'tanda_tangan' => 'https://upload.wikimedia.org/wikipedia/commons/c/c5/Signature_of_William_Shakespeare.svg',
                'foto' => null,
                'created_at' => Carbon::now()->subDays(3)->setHour(8)->setMinute(10),
            ],
            [
                'nakes_jaga_id' => 15,
                'nama' => 'Bagus Pramono, Amd.Kep',
                'instansi' => 'Puskesmas Pondok Aren',
                'keterangan' => 'Hadir tepat waktu',
                'bank' => 'BRI',
                'norek' => '777788889999000',
                'tanda_tangan' => 'https://upload.wikimedia.org/wikipedia/commons/4/4b/Signature_of_Martin_Luther_King_Jr..svg',
                'foto' => null,
                'created_at' => Carbon::now()->subDays(4)->setHour(7)->setMinute(20),
            ],
            [
                'nakes_jaga_id' => 16,
                'nama' => 'dr. Kartini',
                'instansi' => 'RSUD Kota Tangerang',
                'keterangan' => 'Hadir bersama tim',
                'bank' => 'Mandiri',
                'norek' => '1640007777777',
                'tanda_tangan' => 'https://upload.wikimedia.org/wikipedia/commons/3/30/Signature_of_Winston_Churchill.svg',
                'foto' => null,
                'created_at' => Carbon::now()->subDays(4)->setHour(7)->setMinute(30),
            ],
            [
                'nakes_jaga_id' => 17,
                'nama' => 'Toni Hermawan, S.Kep',
                'instansi' => 'RS Hermina Ciputat',
                'keterangan' => 'Membawa tandu',
                'bank' => 'BCA',
                'norek' => '9988776655',
                'tanda_tangan' => 'https://upload.wikimedia.org/wikipedia/commons/0/05/Signature_of_Theodore_Roosevelt.svg',
                'foto' => null,
                'created_at' => Carbon::now()->subDays(5)->setHour(7)->setMinute(10),
            ],
            [
                'nakes_jaga_id' => 18,
                'nama' => 'Ani Susanti, Amd.Kep',
                'instansi' => 'Klinik Sehat Bersama',
                'keterangan' => 'Hadir',
                'bank' => 'BJB',
                'norek' => '001100220033',
                'tanda_tangan' => 'https://upload.wikimedia.org/wikipedia/commons/6/6f/Signature_of_Hillary_Clinton.svg',
                'foto' => null,
                'created_at' => Carbon::now()->subDays(5)->setHour(7)->setMinute(25),
            ],
            [
                'nakes_jaga_id' => 19,
                'nama' => 'dr. Denny Siregar',
                'instansi' => 'RS Sari Asih Ciputat',
                'keterangan' => 'Hadir',
                'bank' => 'BNI',
                'norek' => '1122112211',
                'tanda_tangan' => 'https://upload.wikimedia.org/wikipedia/commons/a/a4/Signature_of_Barack_Obama.svg',
                'foto' => null,
                'created_at' => Carbon::now()->subDays(6)->setHour(8)->setMinute(0),
            ],
            [
                'nakes_jaga_id' => 20,
                'nama' => 'Rina Wati, S.Kep',
                'instansi' => 'RS Premier Bintaro',
                'keterangan' => 'Hadir dengan ambulans 2',
                'bank' => 'BRI',
                'norek' => '123123123123123',
                'tanda_tangan' => 'https://upload.wikimedia.org/wikipedia/commons/f/fa/Signature_of_John_Hancock.png',
                'foto' => null,
                'created_at' => Carbon::now()->subDays(6)->setHour(8)->setMinute(15),
            ],
        ];

        // Format updated_at to be the same as created_at
        foreach ($data as &$row) {
            $row['updated_at'] = clone $row['created_at'];
            $row['created_at'] = $row['created_at']->format('Y-m-d H:i:s');
            $row['updated_at'] = $row['updated_at']->format('Y-m-d H:i:s');
        }

        DB::table('nakes_absens')->insert($data);
    }
}
