[
            ['tanggal' => '2026-11-13', 'cabor' => 'Cricket', 'venue' => 'Lap. Rempas', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-13', 'cabor' => 'Hoki', 'venue' => 'Dwantara', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-13', 'cabor' => 'Menembak', 'venue' => 'WTC Mall Arhanud', 'nakes' => ''],
            ['tanggal' => '2026-11-13', 'cabor' => 'Sepak Bola Putri', 'venue' => 'Lap. Kera Sakti', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-13', 'cabor' => 'Sepak Bola Putra', 'venue' => 'Kodiklat TNI', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-13', 'cabor' => 'Pentathlon', 'venue' => 'Damai Indah Golf BSD', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-14', 'cabor' => 'Bermotor', 'venue' => 'Road Race Dirlantas', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-14', 'cabor' => 'Bermotor', 'venue' => 'Case Track Serpong Paradise', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-14', 'cabor' => 'Bermotor', 'venue' => 'Mini VW Teras Kota', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-14', 'cabor' => 'Cricket', 'venue' => 'Lap. Rempas', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-14', 'cabor' => 'Hoki', 'venue' => 'Dwantara', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-14', 'cabor' => 'Menembak', 'venue' => 'WTC Mall Arhanud', 'nakes' => ''],
            ['tanggal' => '2026-11-14', 'cabor' => 'Panahan', 'venue' => 'ISCI', 'nakes' => ''],
            ['tanggal' => '2026-11-14', 'cabor' => 'Pentathlon', 'venue' => 'Damai Indah Golf BSD', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-14', 'cabor' => 'Sepak Bola Putri', 'venue' => 'Lap. Kera Sakti', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-14', 'cabor' => 'Sepak Bola Putra', 'venue' => 'Kodiklat TNI', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-14', 'cabor' => 'Softball', 'venue' => 'Griya Hijau Alam Sutera', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-16', 'cabor' => 'Catur', 'venue' => 'Blandongan', 'nakes' => ''],
            ['tanggal' => '2026-11-16', 'cabor' => 'Cricket', 'venue' => 'Lap. Rempas', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-16', 'cabor' => 'Hoki', 'venue' => 'Dwantara', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-16', 'cabor' => 'Menembak', 'venue' => 'WTC Mall Arhanud', 'nakes' => ''],
            ['tanggal' => '2026-11-16', 'cabor' => 'Panahan', 'venue' => 'ISCI', 'nakes' => ''],
            ['tanggal' => '2026-11-16', 'cabor' => 'Squash', 'venue' => 'ISCI', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-16', 'cabor' => 'Panjat Tebing', 'venue' => 'PCC', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-16', 'cabor' => 'Pentathlon', 'venue' => 'Damai Indah Golf BSD', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-16', 'cabor' => 'Sepak Bola Putri', 'venue' => 'Lap. Kera Sakti (Perempuan)', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-16', 'cabor' => 'Sepak Bola Putra', 'venue' => 'Kodiklat TNI', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-16', 'cabor' => 'Softball', 'venue' => 'Griya Hijau Alam Sutera', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-17', 'cabor' => 'Anggar', 'venue' => 'UMJ', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-17', 'cabor' => 'Drumband', 'venue' => 'Kodiklat TNI', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-17', 'cabor' => 'Atletik', 'venue' => 'Kodiklat TNI', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-17', 'cabor' => 'Barongsai', 'venue' => 'Plaza Pemkot', 'nakes' => ''],
            ['tanggal' => '2026-11-17', 'cabor' => 'Biliard', 'venue' => 'J Flower', 'nakes' => ''],
            ['tanggal' => '2026-11-17', 'cabor' => 'Bola Basket', 'venue' => 'MS Arena', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-17', 'cabor' => 'Bola Tangan', 'venue' => 'GIS', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-17', 'cabor' => 'Bola Voli', 'venue' => 'UIN', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-17', 'cabor' => 'Bowling', 'venue' => 'WTC', 'nakes' => ''],
            ['tanggal' => '2026-11-17', 'cabor' => 'Catur', 'venue' => 'Blandongan', 'nakes' => ''],
            ['tanggal' => '2026-11-17', 'cabor' => 'Bridge', 'venue' => 'Blandongan', 'nakes' => ''],
            ['tanggal' => '2026-11-17', 'cabor' => 'Bulu Tangkis', 'venue' => 'Candra Wijaya', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-17', 'cabor' => 'Cricket', 'venue' => 'Lap. Rempas', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-17', 'cabor' => 'Dance Sport', 'venue' => 'Bexchange Mall', 'nakes' => ''],
            ['tanggal' => '2026-11-17', 'cabor' => 'Dayung', 'venue' => 'Situ Pondok Jagung', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-17', 'cabor' => 'Esport', 'venue' => 'Gedung UMKM', 'nakes' => ''],
            ['tanggal' => '2026-11-17', 'cabor' => 'Futsal', 'venue' => 'PCC', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-17', 'cabor' => 'Golf', 'venue' => 'Pondok Cabe Golf', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-17', 'cabor' => 'Gymnastic', 'venue' => 'British School', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-17', 'cabor' => 'Hoki', 'venue' => 'Dwantara', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-17', 'cabor' => 'Judo', 'venue' => 'Teras Kota', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-17', 'cabor' => 'Karate', 'venue' => 'Teras Kota', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-17', 'cabor' => 'Tinju', 'venue' => 'Teras Kota', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-17', 'cabor' => 'Kempo', 'venue' => 'Kodiklat TNI', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-17', 'cabor' => 'Sepak Bola Putra', 'venue' => 'Kodiklat TNI', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-17', 'cabor' => 'Kurash', 'venue' => 'GOR BRIN', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-17', 'cabor' => 'Menembak', 'venue' => 'WTC Mall Arhanud', 'nakes' => ''],
            ['tanggal' => '2026-11-17', 'cabor' => 'Muaythai', 'venue' => 'WTC', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-17', 'cabor' => 'Panahan', 'venue' => 'ISCI', 'nakes' => ''],
            ['tanggal' => '2026-11-17', 'cabor' => 'Panjat Tebing', 'venue' => 'PCC', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-17', 'cabor' => 'Pencak Silat', 'venue' => 'GOR BRIN', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-17', 'cabor' => 'Petanque', 'venue' => 'Kec. Pondok Aren', 'nakes' => ''],
            ['tanggal' => '2026-11-17', 'cabor' => 'Pickleball', 'venue' => 'RDM', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-17', 'cabor' => 'Sambo', 'venue' => 'MD Sport', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-17', 'cabor' => 'Selam', 'venue' => 'Damai Indah Golf BSD', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-17', 'cabor' => 'Selancar', 'venue' => 'Sawarna', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-17', 'cabor' => 'Sepak Bola Putri', 'venue' => 'Lap. Kera Sakti', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-17', 'cabor' => 'Tenis Meja', 'venue' => 'Loka Padel', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-17', 'cabor' => 'Sepak Takraw', 'venue' => 'Loka Padel', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-17', 'cabor' => 'Sepatu Roda', 'venue' => 'Ciater Permai', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-17', 'cabor' => 'Softball', 'venue' => 'Griya Hijau Alam Sutera', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-17', 'cabor' => 'Squash', 'venue' => 'ISCI', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-17', 'cabor' => 'Tenis Lapangan', 'venue' => 'Lap. KONI', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-17', 'cabor' => 'Woodball', 'venue' => 'GOR BRIN', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-17', 'cabor' => 'Wushu', 'venue' => 'Plaza Pemkot', 'nakes' => 'Nakes'],
            ['tanggal' => '2026-11-18', 'cabor' => 'Anggar', 'venue' => 'UMJ', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Atletik', 'venue' => 'Kodiklat TNI', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Kempo', 'venue' => 'Kodiklat TNI', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Drumband', 'venue' => 'Kodiklat TNI', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Barongsai', 'venue' => 'Plaza Pemkot', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Biliard', 'venue' => 'J Flower', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Bola Basket', 'venue' => 'MS Arena', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Bola Tangan', 'venue' => 'GIS', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Bola Voli', 'venue' => 'UIN', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Bowling', 'venue' => 'WTC', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Muaythai', 'venue' => 'WTC', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Menembak', 'venue' => 'WTC Mall Arhanud', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Bridge', 'venue' => 'Blandongan', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Catur', 'venue' => 'Blandongan', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Bulu Tangkis', 'venue' => 'Candra Wijaya', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Cricket', 'venue' => 'Lap. Rempas', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Dance Sport', 'venue' => 'Bexchange Mall', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Dayung', 'venue' => 'Situ Pondok Jagung', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Esport', 'venue' => 'Gedung UMKM', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Futsal', 'venue' => 'PCC', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Panjat Tebing', 'venue' => 'PCC', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Golf', 'venue' => 'Pondok Cabe Golf', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Gymnastic', 'venue' => 'British School', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Hoki', 'venue' => 'Dwantara', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Judo', 'venue' => 'Teras Kota', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Karate', 'venue' => 'Teras Kota', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Tinju', 'venue' => 'Teras Kota', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Kurash', 'venue' => 'GOR BRIN', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Woodball', 'venue' => 'GOR BRIN', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Pencak Silat', 'venue' => 'GOR BRIN', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Panahan', 'venue' => 'ISCI', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Squash', 'venue' => 'ISCI', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Petanque', 'venue' => 'Kec. Pondok Aren', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Pickleball', 'venue' => 'RDM', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Sambo', 'venue' => 'MD Sport', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Selam', 'venue' => 'Damai Indah Golf BSD', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Selancar', 'venue' => 'Sawarna', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Sepak Bola', 'venue' => 'Lap. Kera Sakti', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Sepak Takraw', 'venue' => 'Loka Padel', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Tenis Meja', 'venue' => 'Loka Padel', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Sepatu Roda', 'venue' => 'Ciater Permai', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Softball', 'venue' => 'Griya Hijau Alam Sutera', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Tenis Lapangan', 'venue' => 'Lap. KONI', 'nakes' => ''],
            ['tanggal' => '2026-11-18', 'cabor' => 'Wushu', 'venue' => 'Plaza Pemkot', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Anggar', 'venue' => 'UMJ', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Angkat Berat', 'venue' => 'Aula Kec. Pondok Aren', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Angkat Besi', 'venue' => 'ITC BSD', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Arum Jeram', 'venue' => 'Ekowisata Kranggan', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Atletik', 'venue' => 'Kodiklat TNI', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Drumband', 'venue' => 'Kodiklat TNI', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Kempo', 'venue' => 'Kodiklat TNI', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Sepak Bola Putra', 'venue' => 'Kodiklat TNI', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Barongsai', 'venue' => 'Plaza Pemkot', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Biliard', 'venue' => 'J Flower', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Bola Basket', 'venue' => 'MS Arena', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Bola Tangan', 'venue' => 'GIS', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Bola Voli', 'venue' => 'UIN', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Bowling', 'venue' => 'WTC', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Bridge', 'venue' => 'Blandongan', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Catur', 'venue' => 'Blandongan', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Bulu Tangkis', 'venue' => 'Candra Wijaya', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Cricket', 'venue' => 'Lap. Rempas', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Dayung', 'venue' => 'Situ Pondok Jagung', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Esport', 'venue' => 'Gedung UMKM', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Futsal', 'venue' => 'PCC', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Rugby', 'venue' => 'PCC', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Panjat Tebing', 'venue' => 'PCC', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Golf', 'venue' => 'Pondok Cabe Golf', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Gymnastic', 'venue' => 'British School', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Hoki', 'venue' => 'Dwantara', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Karate', 'venue' => 'Teras Kota', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Tinju', 'venue' => 'Teras Kota', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Muaythai', 'venue' => 'WTC', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Panahan', 'venue' => 'ISCI', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Pencak Silat', 'venue' => 'GOR BRIN', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Petanque', 'venue' => 'Kec. Pondok Aren', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Pickleball', 'venue' => 'RDM', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Selancar', 'venue' => 'Sawarna', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Sepak Bola Putri', 'venue' => 'Lap. Kera Sakti', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Tenis Meja', 'venue' => 'Loka Padel', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Sepak Takraw', 'venue' => 'Loka Padel', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Sepatu Roda', 'venue' => 'Ciater Permai', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Softball', 'venue' => 'Griya Hijau Alam Sutera', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Squash', 'venue' => 'ISCI', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Tenis Lapangan', 'venue' => 'Lap. KONI', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Woodball', 'venue' => 'GOR BRIN', 'nakes' => ''],
            ['tanggal' => '2026-11-19', 'cabor' => 'Wushu', 'venue' => 'Plaza Pemkot', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Anggar', 'venue' => 'UMJ', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Angkat Berat', 'venue' => 'Aula Kec. Pondok Aren', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Angkat Besi', 'venue' => 'ITC BSD', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Renang', 'venue' => 'Damai Indah Golf BSD', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Arum Jeram', 'venue' => 'Ekowisata Kranggan', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Barongsai', 'venue' => 'Plaza Pemkot', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Wushu', 'venue' => 'Plaza Pemkot', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Biliard', 'venue' => 'J Flower', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Bola Basket', 'venue' => 'MS Arena', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Bola Tangan', 'venue' => 'GIS', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Bola Voli', 'venue' => 'UIN', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Bowling', 'venue' => 'WTC', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Bridge', 'venue' => 'Blandongan', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Catur', 'venue' => 'Blandongan', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Bulu Tangkis', 'venue' => 'Candra Wijaya', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Cricket', 'venue' => 'Lap. Rempas', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Dayung', 'venue' => 'Situ Pondok Jagung', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Sepak Bola Putra', 'venue' => 'Kodiklat TNI', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Drumband', 'venue' => 'Kodiklat TNI', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Esport', 'venue' => 'Gedung UMKM', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Floorball', 'venue' => 'GIS', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Futsal', 'venue' => 'PCC', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Rugby', 'venue' => 'PCC', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Golf', 'venue' => 'Pondok Cabe Golf', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Gulat', 'venue' => 'MD Sport', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Gymnastic', 'venue' => 'British School', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Hoki', 'venue' => 'Dwantara', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'MMA', 'venue' => 'GOR Ciputat', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Panahan', 'venue' => 'ISCI', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Squash', 'venue' => 'ISCI', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Panjat Tebing', 'venue' => 'PCC', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Pencak Silat', 'venue' => 'GOR BRIN', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Tarung Derajat', 'venue' => 'GOR BRIN', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Woodball', 'venue' => 'GOR BRIN', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Petanque', 'venue' => 'Kec. Pondok Aren', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Selancar', 'venue' => 'Sawarna', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Sepak Bola', 'venue' => 'Lap. Kera Sakti', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Tenis Meja', 'venue' => 'Loka Padel', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Sepak Takraw', 'venue' => 'Loka Padel', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Sepatu Roda', 'venue' => 'Ciater Permai', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Softball', 'venue' => 'Griya Hijau Alam Sutera', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Taekwondo', 'venue' => '—', 'nakes' => ''],
            ['tanggal' => '2026-11-20', 'cabor' => 'Tenis Lapangan', 'venue' => 'Lap. KONI', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Angkat Besi', 'venue' => 'ITC BSD', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Renang', 'venue' => 'Damai Indah Golf BSD', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Arum Jeram', 'venue' => 'Ekowisata Kranggan', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Barongsai', 'venue' => 'Plaza Pemkot', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Bermotor', 'venue' => 'Road Race Dirlantas', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Bermotor', 'venue' => 'Case Track Serpong Paradise', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Bermotor', 'venue' => 'Mini VW Teras Kota', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Biliard', 'venue' => 'J Flower', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Bola Basket', 'venue' => 'MS Arena', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Bola Tangan', 'venue' => 'GIS', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Floorball', 'venue' => 'GIS', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Bridge', 'venue' => 'Blandongan', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Catur', 'venue' => 'Blandongan', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Bulu Tangkis', 'venue' => 'Candra Wijaya', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Cricket', 'venue' => 'Lap. Rempas', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Dayung', 'venue' => 'Situ Pondok Jagung', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Drumband', 'venue' => 'Kodiklat TNI', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Sepak Bola Putra', 'venue' => 'Kodiklat TNI', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Gateball', 'venue' => 'Kampus Kademangan', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Golf', 'venue' => 'Pondok Cabe Golf', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Gulat', 'venue' => 'MD Sport', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Gymnastic', 'venue' => 'British School', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Hoki', 'venue' => 'Dwantara', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'MMA', 'venue' => 'GOR Ciputat', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Jujitsu', 'venue' => 'GOR Ciputat', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Panahan', 'venue' => 'ISCI', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Squash', 'venue' => 'ISCI', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Rugby', 'venue' => 'PCC', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Panjat Tebing', 'venue' => 'PCC', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Futsal', 'venue' => 'PCC', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Petanque', 'venue' => 'Kec. Pondok Aren', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Sepak Bola Putri', 'venue' => 'Lap. Kera Sakti', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Sepatu Roda', 'venue' => 'Ciater Permai', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Softball', 'venue' => 'Griya Hijau Alam Sutera', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Taekwondo', 'venue' => '—', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Tarung Derajat', 'venue' => 'GOR BRIN', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Woodball', 'venue' => 'GOR BRIN', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Pencak Silat', 'venue' => 'GOR BRIN', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Tenis Lapangan', 'venue' => 'Lap. KONI', 'nakes' => ''],
            ['tanggal' => '2026-11-21', 'cabor' => 'Tenis Meja', 'venue' => 'Lokal Padel', 'nakes' => ''],
            ['tanggal' => '2026-11-22', 'cabor' => 'Renang', 'venue' => 'Damai Indah Golf BSD', 'nakes' => ''],
            ['tanggal' => '2026-11-22', 'cabor' => 'Arum Jeram', 'venue' => 'Ekowisata Kranggan', 'nakes' => ''],
            ['tanggal' => '2026-11-22', 'cabor' => 'Bermotor', 'venue' => 'Road Race Dirlantas', 'nakes' => ''],
            ['tanggal' => '2026-11-22', 'cabor' => 'Bermotor', 'venue' => 'Case Track Serpong Paradise', 'nakes' => ''],
            ['tanggal' => '2026-11-22', 'cabor' => 'Bermotor', 'venue' => 'Teras Kota', 'nakes' => ''],
            ['tanggal' => '2026-11-22', 'cabor' => 'Bina Raga', 'venue' => 'Teras Kota', 'nakes' => ''],
            ['tanggal' => '2026-11-22', 'cabor' => 'Bola Tangan', 'venue' => 'GIS', 'nakes' => ''],
            ['tanggal' => '2026-11-22', 'cabor' => 'Bridge', 'venue' => 'Blandongan', 'nakes' => ''],
            ['tanggal' => '2026-11-22', 'cabor' => 'Catur', 'venue' => 'Blandongan', 'nakes' => ''],
            ['tanggal' => '2026-11-22', 'cabor' => 'Bulu Tangkis', 'venue' => 'Candra Wijaya', 'nakes' => ''],
            ['tanggal' => '2026-11-22', 'cabor' => 'Cricket', 'venue' => 'Lap. Rempas', 'nakes' => ''],
            ['tanggal' => '2026-11-22', 'cabor' => 'Dayung', 'venue' => 'Situ Pondok Jagung', 'nakes' => ''],
            ['tanggal' => '2026-11-22', 'cabor' => 'Drumband', 'venue' => 'Kodiklat TNI', 'nakes' => ''],
            ['tanggal' => '2026-11-22', 'cabor' => 'Floorball', 'venue' => 'GIS', 'nakes' => ''],
            ['tanggal' => '2026-11-22', 'cabor' => 'Gateball', 'venue' => 'Kampus Kademangan', 'nakes' => ''],
            ['tanggal' => '2026-11-22', 'cabor' => 'Gulat', 'venue' => 'MD Sport', 'nakes' => ''],
            ['tanggal' => '2026-11-22', 'cabor' => 'Hoki', 'venue' => 'Dwantara', 'nakes' => ''],
            ['tanggal' => '2026-11-22', 'cabor' => 'MMA', 'venue' => 'GOR Ciputat', 'nakes' => ''],
            ['tanggal' => '2026-11-22', 'cabor' => 'Panahan', 'venue' => 'ISCI', 'nakes' => ''],
            ['tanggal' => '2026-11-22', 'cabor' => 'Squash', 'venue' => 'ISCI', 'nakes' => ''],
            ['tanggal' => '2026-11-22', 'cabor' => 'Panjat Tebing', 'venue' => 'PCC', 'nakes' => ''],
            ['tanggal' => '2026-11-22', 'cabor' => 'Rugby', 'venue' => 'PCC', 'nakes' => ''],
            ['tanggal' => '2026-11-22', 'cabor' => 'Futsal', 'venue' => 'PCC', 'nakes' => ''],
            ['tanggal' => '2026-11-22', 'cabor' => 'Sepak Bola', 'venue' => 'Lap. Kera Sakti', 'nakes' => ''],
            ['tanggal' => '2026-11-22', 'cabor' => 'Sepatu Roda', 'venue' => 'Ciater Permai', 'nakes' => ''],
            ['tanggal' => '2026-11-22', 'cabor' => 'Softball', 'venue' => 'Griya Hijau Alam Sutera', 'nakes' => ''],
            ['tanggal' => '2026-11-22', 'cabor' => 'Tarung Derajat', 'venue' => 'GOR BRIN', 'nakes' => ''],
            ['tanggal' => '2026-11-22', 'cabor' => 'Woodball', 'venue' => 'GOR BRIN', 'nakes' => ''],
        ]